root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -ldflags='-s -w' -o ./tmp/main ."
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go", "_mock.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 100
  rerun = false
  rerun_delay = 0
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true
  silent = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = false

[proxy]
  enabled = false
  app_port = 8080
  proxy_port = 0
