# build stage
FROM golang:1.25-alpine AS build

# set working directory
WORKDIR /app

# copy source code
COPY . .

# install dependencies
RUN go mod download

# build binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/api ./cmd/api/main.go

# final stage
FROM scratch:latest AS final
LABEL maintainer="go@thadeu.org"

RUN apk --no-cache add ca-certificates

# set working directory
WORKDIR /app

# copy binary
COPY --from=build /app/bin/api ./

EXPOSE 8080

ENTRYPOINT [ "./api" ]