version: '3' # https://taskfile.dev/

dotenv: ['.env']

tasks:
  default:
    deps: [test]

  test:
    aliases: [t]
    cmds:
      - bin/gotest --format-hide-empty-pkg
  
  test-watch:
    aliases: [tw]
    cmds:
      - task: test
      - bin/gotest --watch --format testdox --format-hide-empty-pkg

  cover:
    cmds:
      - go test ./... -json -cover | tparse -all

  dev:
    dotenv: ['.env']
    # deps: [test]
    cmds:
      - air -c .air.api.toml

  build-all:
    cmds:
      - go build -o ./tmp/api ./cmd/api

  # Example to run generate a new migration
  # task g:migration -- create_todos_table
  g:migration:
    dir: db
    silent: true
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}
  
  # task migrate:up
  migrate:up:
    aliases: [mu]
    dir: db
    silent: true
    cmds:
      - echo "Running migrations up..."
      - migrate -database $DATABASE_URL -path migrations up

  # task migrate:up
  migrate:down:
    aliases: [md]
    dir: db
    silent: true
    cmds:
      - echo "Running migrations down..."
      - migrate -database $DATABASE_URL -path migrations down

  # Monitoring tasks
  monitoring:setup:
    aliases: [mon:setup]
    cmds:
      - echo "Setting up monitoring services..."
      - ./scripts/setup-monitoring.sh

  monitoring:start:
    aliases: [mon:start]
    cmds:
      - echo "Starting monitoring services..."
      - docker-compose up -d

  monitoring:stop:
    aliases: [mon:stop]
    cmds:
      - echo "Stopping monitoring services..."
      - docker-compose down

  monitoring:logs:
    aliases: [mon:logs]
    cmds:
      - docker-compose logs -f

  monitoring:status:
    aliases: [mon:status]
    cmds:
      - docker-compose ps

  # Run application with monitoring
  run:monitored:
    aliases: [run:mon]
    cmds:
      # - echo "Starting TodoApp with monitoring..."
      # - echo "Grafana: http://localhost:3000 (admin/admin123)"
      # - echo "Prometheus: http://localhost:9090"
      # - echo "Metrics: http://localhost:9091"
      - task: dev