# https://taskfile.dev/

version: '3'

tasks:
  default:
    deps: [test]
    cmds:
      - task: dev

  test:
    aliases: [t]
    cmds:
      - gotest || bin/gotest
  
  test-watch:
    aliases: [tw]
    cmds:
      - task: test
      - gotest --watch --format testdox

  cover:
    cmds:
      - go test ./... -json -cover | tparse -all

  dev:
    dotenv: ['.env']
    cmds:
      - air -c .air.toml

  build:
    cmds:
      - go build -ldflags='-s -w' -o ./tmp/main .