version: '3' # https://taskfile.dev/

dotenv: ['.env']

tasks:
  default:
    deps: [test]
    # cmds:
    #   - task: dev

  test:
    aliases: [t]
    cmds:
      - bin/gotest --format-hide-empty-pkg
  
  test-watch:
    aliases: [tw]
    cmds:
      - task: test
      - gotest --watch --format testdox --format-hide-empty-pkg

  cover:
    cmds:
      - go test ./... -json -cover | tparse -all

  dev:
    dotenv: ['.env']
    deps: [test]
    cmds:
      - air -c .air.api.toml

  build-all:
    cmds:
      - go build -o ./tmp/api ./cmd/api

  # Example to run generate a new migration
  # task g:migration -- create_todos_table
  g:migration:
    dir: db
    silent: true
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}
  
  # task migrate:up
  migrate:up:
    aliases: [mu]
    dir: db
    silent: true
    cmds:
      - echo "Running migrations up..."
      - migrate -database $DATABASE_URL -path migrations up

  # task migrate:up
  migrate:down:
    aliases: [md]
    dir: db
    silent: true
    cmds:
      - echo "Running migrations down..."
      - migrate -database $DATABASE_URL -path migrations down