global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'todoapp'
    static_configs:
      - targets: ['host.docker.internal:9091']  # Porta das métricas da aplicação
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Node exporter para métricas do sistema (opcional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s
